#!/usr/bin/env python3
"""Regenerate the grid-derived blocks of book_context/book_context_B0N.json.

Three blocks are derived from grids/milestones_payoffs.csv and nothing else:

- ``exit_state_locks``: the active (not retired) milestones whose target_book is
  this book, in grid order, with act and episode/range as coordinates;
- ``entry_state`` (B02-B09): the preceding book's exit locks, cited by ID;
- ``continuity_hooks``: every cross-book ``required_setups`` edge between active
  rows, as ``owes_forward`` in the earlier book and ``collects`` in the later one.

Every other key is left exactly as it is. Descriptions and statuses live in the
grid and are not copied here. Rows with no target_book land in no book and are
reported. Run from anywhere; ``--check`` exits 1 if any file would change.

Added 2026-09-26 (ledger 118) after the book contexts had been regenerated by
hand, which left B02 and B03 stale.
"""
import argparse
import csv
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GRID = os.path.join(REPO, "grids", "milestones_payoffs.csv")
BOOKS = [f"B{n:02d}" for n in range(1, 10)]
STAMP = "2026-09-26"
SOURCE = "grids/milestones_payoffs.csv"


def load_grid():
    with open(GRID, encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    active = [r for r in rows if r["status"].strip().lower() != "retired"]
    return rows, active


def setups(row):
    return [s.strip() for s in row["required_setups"].split(",") if s.strip()]


def derive(active):
    by_id = {r["milestone_id"]: r for r in active}
    locks = {b: [] for b in BOOKS}
    unplaced = []
    for r in active:
        book = r["target_book"].strip()
        if book not in locks:
            unplaced.append(r["milestone_id"])
            continue
        lock = {"milestone": r["milestone_id"]}
        if r["target_act"].strip():
            lock["act"] = r["target_act"].strip()
        if r["target_episode_or_range"].strip():
            lock["episode"] = r["target_episode_or_range"].strip()
        locks[book].append(lock)

    owes = {b: [] for b in BOOKS}
    collects = {b: [] for b in BOOKS}
    backward = []
    for r in active:
        book = r["target_book"].strip()
        for s in setups(r):
            src = by_id.get(s)
            if src is None:  # retired or missing; the validator reports missing
                continue
            sbook = src["target_book"].strip()
            if book not in owes or sbook not in owes or sbook == book:
                continue
            if BOOKS.index(sbook) > BOOKS.index(book):
                backward.append((r["milestone_id"], s))
            owes[sbook].append({"kind": "owes_forward", "milestone": s,
                                "required_by": r["milestone_id"], "in_book": book})
            collects[book].append({"kind": "collects", "milestone": r["milestone_id"],
                                   "requires": s, "from_book": sbook})
    return locks, owes, collects, unplaced, backward


def rebuild(book, data, locks, owes, collects):
    i = BOOKS.index(book)
    data["exit_state_locks"] = [{
        "_basis": "derived",
        "_derivation": f"DERIVED {STAMP} by tools/derive_book_context.py from {SOURCE}: "
                       "the active (not retired) milestones landing in this book are what it "
                       "locks on exit. Structural coordinates only; descriptions and statuses "
                       "live in the grid. Regenerate with the tool, never by hand.",
        "_status": "mixed - each lock inherits its row's status in the grid",
    }] + locks[book]
    if i > 0:
        prev = BOOKS[i - 1]
        ids = [l["milestone"] for l in locks[prev]]
        es = data["entry_state"]
        es["_basis"] = "derived"
        es["_derivation"] = (f"DERIVED {STAMP} by tools/derive_book_context.py: a book's entry "
                             f"state is the preceding book's exit state, so this cites "
                             f"{prev}'s exit_state_locks rather than restating them.")
        es["_status"] = "mixed - inherited from the grid rows"
        es["inherits_from"] = prev
        es["carried_in_locks"] = ids
        es["world"] = (f"DERIVED: the world as {prev} leaves it. See book_context_{prev}.json "
                       f"exit_state_locks: {', '.join(ids) if ids else 'none'}.")
    data["continuity_hooks"] = [{
        "_basis": "derived",
        "_derivation": f"DERIVED {STAMP} by tools/derive_book_context.py from {SOURCE} "
                       "required_setups between active rows. A cross-book dependency is a "
                       "continuity hook. Milestone IDs are cited, not described.",
        "_counts": {"owes_forward": len(owes[book]), "collects": len(collects[book])},
    }] + owes[book] + collects[book]
    return data


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = ap.parse_args()
    _, active = load_grid()
    locks, owes, collects, unplaced, backward = derive(active)
    drift = []
    for book in BOOKS:
        path = os.path.join(REPO, "book_context", f"book_context_{book}.json")
        with open(path, encoding="utf-8") as fh:
            before = fh.read()
        data = rebuild(book, json.loads(before), locks, owes, collects)
        after = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
        if after != before:
            drift.append(book)
            if not args.check:
                with open(path, "w", encoding="utf-8", newline="\n") as fh:
                    fh.write(after)
    print(("drift: " if args.check else "rewritten: ") + (", ".join(drift) or "none"))
    if unplaced:
        print("no target_book (in no book's locks): " + ", ".join(unplaced))
    if backward:
        print("BACKWARD setups (setup lands after its dependant): "
              + ", ".join(f"{a}<-{b}" for a, b in backward))
    return 1 if (args.check and drift) else 0


if __name__ == "__main__":
    sys.exit(main())
